Update references and terms
SMPTE/ag-02 pull request #14
Opened 2022-12-23 19:31 UTC by SteveLLamb

First pass update refs, closes #4

2023-03-24 18:12 UTC, palemieux requested changes

2023-03-24 18:12 UTC, palemieux commented on doc/main.html
> +        All Engineering Documents should follow the guidelines of the <a href="#bib-iso-directives"></a> with the following exceptions: In the event of a conflict, explicit provisions of <a href="#bi
This should be a reference to Part 2 only: SMPTE does not follow Part 1.

2023-03-24 18:12 UTC, palemieux commented on doc/main.html
> +            Any document conforming to <a href="#bib-w3c-xml-10-5ed"></a> or <a href="#bib-w3c-xml-11-2ed"></a> may be submitted.
We should leave undated, i.e. point to the latest edition.

See https://doc.smpte-doc.org/st429-10-private/main/#sec-normative-references

2023-03-24 18:46 UTC, SteveLLamb commented
@palemieux changes requested via https://github.com/SMPTE/ag-02/pull/14/commits/9f4b3395927ae57c8ea52753d597b7a8b5eeb49b

2023-03-24 21:09 UTC, palemieux approved these changes

2023-03-24 22:58 UTC, SteveLLamb commented
Notice to be sent to ST - this PR is under 2-week review, and will be merged on 2023-04-10 if no objections.

2023-05-09 21:09 UTC, SteveLLamb commented
Merging as per above, no objections from ST.

2023-05-09 21:09 UTC, merged